Update all dependencies
I first updated `toml` to 0.7.3, but this caused

    error[E0631]: type mismatch in function arguments
        --> src/bin/mdbook-gettext.rs:80:45
         |
    80   |     let po_dir = cfg.get("po-dir").and_then(Value::as_str).unwrap_or("po");
         |                                    -------- ^^^^^^^^^^^^^
         |                                    |        |
         |                                    |        expected due to this
         |                                    |        found signature defined here
         |                                    required by a bound introduced by this call
         |
         = note: expected function signature `fn(&toml::value::Value) -> _`
                    found function signature `for<'a> fn(&'a toml::Value) -> _`
    note: required by a bound in `Option::<T>::and_then`

It turned out I could remove the explicit dependency completely,
though.